dotenv: .env
dependencies:
  - Uniswap/v2-core@1.0.1
  - Uniswap/solidity-lib@4.0.0-alpha
  - Uniswap/v2-periphery@1.0.0-beta.0

compiler:
  solc:
    version: 0.6.6
    remappings:
      - "@uniswap/v2-core=Uniswap/v2-core@1.0.1"
      - "@uniswap/lib=Uniswap/solidity-lib@4.0.0-alpha"
      - "@uniswap/v2-periphery=Uniswap/v2-periphery@1.0.0-beta.0"
wallets:
  from_key: ${PRIVATE_KEY}
